export default {
  A: [
    {
      id: 'aaa',
      name: 'A',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 0,
        },
        {
          string: 2,
          fret: 2,
        },
        {
          string: 3,
          fret: 2,
        },
        {
          string: 4,
          fret: 2,
        },
        {
          string: 5,
          fret: 0,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'bbb',
      name: '',
      firstFret: 4,
      frets: 3,
      hasBarre: true,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 2,
        },
        {
          string: 4,
          fret: 3,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'ccc',
      name: '',
      firstFret: 6,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 3,
        },
        {
          string: 2,
          fret: 4,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],
  A5: [
    {
      id: 'jjj5',
      name: 'A5',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: null,
        },
        {
          string: 2,
          fret: null,
        },
        {
          string: 3,
          fret: null,
        },
        {
          string: 4,
          fret: 2,
        },
        {
          string: 5,
          fret: 0,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'kkk5',
      name: '',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: null,
        },
        {
          string: 2,
          fret: null,
        },
        {
          string: 3,
          fret: null,
        },
        {
          string: 4,
          fret: null,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'lll5',
      name: '',
      firstFret: 6,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: null,
        },
        {
          string: 2,
          fret: null,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],
  A7: [
    {
      id: 'jjj',
      name: 'A7',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 0,
        },
        {
          string: 2,
          fret: 2,
        },
        {
          string: 3,
          fret: 0,
        },
        {
          string: 4,
          fret: 2,
        },
        {
          string: 5,
          fret: 0,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'kkk',
      name: '',
      firstFret: 4,
      frets: 3,
      hasBarre: true,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 2,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'lll',
      name: '',
      firstFret: 6,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 3,
        },
        {
          string: 2,
          fret: 2,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],
  Adiez: [
    {
      id: 'aaadiez',
      name: 'A-#',
      firstFret: 0,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 3,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 3,
        },
        {
          string: 5,
          fret: 1,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'bbbdiez',
      name: '',
      firstFret: 5,
      frets: 3,
      hasBarre: true,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 2,
        },
        {
          string: 4,
          fret: 3,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'cccdiez',
      name: '',
      firstFret: 7,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 3,
        },
        {
          string: 2,
          fret: 4,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],
  Adiez7: [
    {
      id: 'jjjdiez',
      name: 'A-#-7',
      firstFret: 0,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 3,
        },
        {
          string: 3,
          fret: 1,
        },
        {
          string: 4,
          fret: 3,
        },
        {
          string: 5,
          fret: 1,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'kkkdiez',
      name: '',
      firstFret: 5,
      frets: 3,
      hasBarre: true,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 2,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'llldiez',
      name: '',
      firstFret: 7,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 3,
        },
        {
          string: 2,
          fret: 2,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],

  B: [
    {
      id: 'baa',
      name: 'B',
      firstFret: 1,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  C: [
    {
      id: 'caa',
      name: 'C',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 0 },
        { string: 2, fret: 1 },
        { string: 3, fret: 0 },
        { string: 4, fret: 2 },
        { string: 5, fret: 3 },
        { string: 6, fret: null },
      ],
    },
  ],
  Cdiez: [
    {
      id: 'caadiez',
      name: 'C-#',
      firstFret: 0,
      frets: 4,
      hasBarre: true,
      barreShort: 3,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 4 },
        { string: 6, fret: null },
      ],
    },
  ],
  D: [
    {
      id: 'daa',
      name: 'D',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 2 },
        { string: 2, fret: 3 },
        { string: 3, fret: 2 },
        { string: 4, fret: 0 },
        { string: 5, fret: null },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'dcadiez',
      name: '',
      firstFret: 1,
      frets: 4,
      hasBarre: true,
      barreShort: 3,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 4 },
        { string: 6, fret: null },
      ],
    },
  ],
  Ddiez: [
    {
      id: 'daadiez',
      name: 'D-#',
      firstFret: 0,
      frets: 4,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 4 },
        { string: 3, fret: 3 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'dcaadiez',
      name: '',
      firstFret: 2,
      frets: 4,
      hasBarre: true,
      barreShort: 3,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 4 },
        { string: 6, fret: null },
      ],
    },
  ],
  E: [
    {
      id: 'eaa',
      name: 'E',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 0 },
        { string: 2, fret: 0 },
        { string: 3, fret: 1 },
        { string: 4, fret: 2 },
        { string: 5, fret: 2 },
        { string: 6, fret: 0 },
      ],
    },
  ],
  F: [
    {
      id: 'faa',
      name: 'F',
      firstFret: 0,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiez: [
    {
      id: 'faadiez',
      name: 'F-#',
      firstFret: 1,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  G: [
    {
      id: 'gaa',
      name: 'G',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 3 },
        { string: 3, fret: 0 },
        { string: 4, fret: 0 },
        { string: 5, fret: 2 },
        { string: 6, fret: 3 },
      ],
    },
    {
      id: 'gbb',
      name: '',
      firstFret: 2,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiez: [
    {
      id: 'gaadiez',
      name: '',
      firstFret: 3,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
    {
      id: 'gbbdiez',
      name: 'G-#',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 3 },
        { string: 3, fret: 0 },
        { string: 4, fret: 0 },
        { string: 5, fret: 2 },
        { string: 6, fret: 3 },
      ],
    },
  ],

  Am: [
    {
      id: 'ddd',
      name: 'Am',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 0,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 2,
        },
        {
          string: 4,
          fret: 2,
        },
        {
          string: 5,
          fret: 0,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'eee',
      name: '',
      firstFret: 4,
      frets: 3,
      hasBarre: true,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 1,
        },
        {
          string: 4,
          fret: 3,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'fff',
      name: '',
      firstFret: 6,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 2,
        },
        {
          string: 2,
          fret: 4,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],
  Am5: [
    {
      id: 'jjjm5',
      name: 'Am5',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: null,
        },
        {
          string: 2,
          fret: null,
        },
        {
          string: 3,
          fret: null,
        },
        {
          string: 4,
          fret: 2,
        },
        {
          string: 5,
          fret: 0,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'kkkm5',
      name: '',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: null,
        },
        {
          string: 2,
          fret: null,
        },
        {
          string: 3,
          fret: null,
        },
        {
          string: 4,
          fret: null,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'lllm5',
      name: '',
      firstFret: 6,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: null,
        },
        {
          string: 2,
          fret: null,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],
  Am7: [
    {
      id: 'ggg',
      name: 'Am7 ',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 0,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 0,
        },
        {
          string: 4,
          fret: 2,
        },
        {
          string: 5,
          fret: 0,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'hhh',
      name: '',
      firstFret: 4,
      frets: 3,
      hasBarre: true,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 1,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'iii',
      name: '',
      firstFret: 6,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 2,
        },
        {
          string: 2,
          fret: 2,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],

  Adiezm: [
    {
      id: 'ddddiez',
      name: 'A-#-m',
      firstFret: 0,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 2,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 3,
        },
        {
          string: 5,
          fret: 1,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'eeediez',
      name: '',
      firstFret: 5,
      frets: 3,
      hasBarre: true,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 1,
        },
        {
          string: 4,
          fret: 3,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'fffdiez',
      name: '',
      firstFret: 7,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 2,
        },
        {
          string: 2,
          fret: 4,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],
  Adiezm7: [
    {
      id: 'gggdiez',
      name: 'A-#-m7 ',
      firstFret: 0,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 2,
        },
        {
          string: 3,
          fret: 1,
        },
        {
          string: 4,
          fret: 3,
        },
        {
          string: 5,
          fret: 1,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
    {
      id: 'hhhdiez',
      name: '',
      firstFret: 5,
      frets: 3,
      hasBarre: true,
      points: [
        {
          string: 1,
          fret: 1,
        },
        {
          string: 2,
          fret: 1,
        },
        {
          string: 3,
          fret: 1,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: 3,
        },
        {
          string: 6,
          fret: 1,
        },
      ],
    },
    {
      id: 'iiidiez',
      name: '',
      firstFret: 7,
      frets: 4,
      hasBarre: false,
      points: [
        {
          string: 1,
          fret: 2,
        },
        {
          string: 2,
          fret: 2,
        },
        {
          string: 3,
          fret: 3,
        },
        {
          string: 4,
          fret: 1,
        },
        {
          string: 5,
          fret: null,
        },
        {
          string: 6,
          fret: null,
        },
      ],
    },
  ],

  Bm: [
    {
      id: 'baam',
      name: 'Bm',
      firstFret: 1,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  Cm: [
    {
      id: 'cma',
      name: 'Cm',
      firstFret: 2,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  Cdiezm: [
    {
      id: 'caadiezm',
      name: 'C-#-m',
      firstFret: 3,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  Dm: [
    {
      id: 'daam',
      name: 'Dm',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 2 },
        { string: 4, fret: 0 },
        { string: 5, fret: null },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'dma',
      name: '',
      firstFret: 4,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  Em: [
    {
      id: 'eaam',
      name: 'Em',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 0 },
        { string: 2, fret: 0 },
        { string: 3, fret: 0 },
        { string: 4, fret: 2 },
        { string: 5, fret: 2 },
        { string: 6, fret: 0 },
      ],
    },
    {
      id: 'ema',
      name: '',
      firstFret: 6,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  Fm: [
    {
      id: 'faam',
      name: 'Fm',
      firstFret: 0,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
    {
      id: 'faa2m',
      name: '',
      firstFret: 7,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  Fdiezm: [
    {
      id: 'faadiez1m',
      name: 'F-#-m',
      firstFret: 1,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
    {
      id: 'faadiezm',
      name: '',
      firstFret: 8,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  Gm: [
    {
      id: 'gaam',
      name: 'Gm',
      firstFret: 2,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],

  B7: [
    {
      id: 'b7a',
      name: 'B7',
      firstFret: 1,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'b7b',
      name: '',
      firstFret: 6,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  C7: [
    {
      id: 'c7a',
      name: 'C7',
      firstFret: 2,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'c7b',
      name: '',
      firstFret: 7,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiez7: [
    {
      id: 'cdiez7a',
      name: 'C-#-7',
      firstFret: 3,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'cdiez7b',
      name: '',
      firstFret: 8,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  D7: [
    {
      id: 'd7a',
      name: 'D7',
      firstFret: 4,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'd7b',
      name: '',
      firstFret: 9,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiez7: [
    {
      id: 'ddiez7a',
      name: 'D-#-7',
      firstFret: 5,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'ddiez7b',
      name: '',
      firstFret: 10,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  E7: [
    {
      id: 'e7a',
      name: 'E7',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 0 },
        { string: 2, fret: 0 },
        { string: 3, fret: 1 },
        { string: 4, fret: 0 },
        { string: 5, fret: 2 },
        { string: 6, fret: 0 },
      ],
    },
    {
      id: 'e7b',
      name: '',
      firstFret: 6,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  F7: [
    {
      id: 'f7a',
      name: 'F7',
      firstFret: 7,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'f7b',
      name: '',
      firstFret: 0,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiez7: [
    {
      id: 'fdiez7a',
      name: 'F-#-7',
      firstFret: 8,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'fdiez7b',
      name: '',
      firstFret: 1,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  G7: [
    {
      id: 'g7a',
      name: 'G7',
      firstFret: 9,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'g7b',
      name: '',
      firstFret: 2,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiez7: [
    {
      id: 'gdiez7a',
      name: 'G-#-7',
      firstFret: 10,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'gdiez7b',
      name: '',
      firstFret: 3,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Bm7: [
    {
      id: 'bm7a',
      name: 'Bm7',
      firstFret: 1,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'bm7b',
      name: '',
      firstFret: 6,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cm7: [
    {
      id: 'cm7a',
      name: 'Cm7',
      firstFret: 2,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'cm7b',
      name: '',
      firstFret: 7,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiezm7: [
    {
      id: 'cdiezm7a',
      name: 'C-#-m7',
      firstFret: 3,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'cdiezm7b',
      name: '',
      firstFret: 8,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Dm7: [
    {
      id: 'dm7a',
      name: 'Dm7',
      firstFret: 4,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'dm7b',
      name: '',
      firstFret: 9,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiezm7: [
    {
      id: 'ddiezm7a',
      name: 'D-#-m7',
      firstFret: 5,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'ddiezm7b',
      name: '',
      firstFret: 10,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Em7: [
    {
      id: 'em7a',
      name: 'Em7',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 0 },
        { string: 2, fret: 0 },
        { string: 3, fret: 0 },
        { string: 4, fret: 0 },
        { string: 5, fret: 2 },
        { string: 6, fret: 0 },
      ],
    },
    {
      id: 'em7b',
      name: '',
      firstFret: 6,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  Fm7: [
    {
      id: 'fm7a',
      name: 'Fm7',
      firstFret: 7,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'fm7b',
      name: '',
      firstFret: 0,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiezm7: [
    {
      id: 'fdiezm7a',
      name: 'F-#-m7',
      firstFret: 8,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'fdiezm7b',
      name: '',
      firstFret: 1,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gm7: [
    {
      id: 'gm7a',
      name: 'Gm7',
      firstFret: 9,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'gm7b',
      name: '',
      firstFret: 2,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiezm7: [
    {
      id: 'gdiezm7a',
      name: 'G-#-m7',
      firstFret: 10,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'gdiezm7b',
      name: '',
      firstFret: 3,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adiez5: [
    {
      id: 'adiez5a',
      name: 'A-#-5',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'adiez5b',
      name: '',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  B5: [
    {
      id: 'b5a',
      name: 'B5',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'b5b',
      name: '',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  C5: [
    {
      id: 'c5a',
      name: 'C5',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'c5b',
      name: '',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiez5: [
    {
      id: 'cdiez5a',
      name: 'C-#-5',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'cdiez5b',
      name: '',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  D5: [
    {
      id: 'd5a',
      name: 'D5',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'd5b',
      name: '',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiez5: [
    {
      id: 'ddiez5a',
      name: 'D-#-5',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'ddiez5b',
      name: '',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  E5: [
    {
      id: 'e5a',
      name: 'E5',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 2 },
        { string: 6, fret: 0 },
      ],
    },
    {
      id: 'e5b',
      name: '',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
  ],
  F5: [
    {
      id: 'f5a',
      name: 'F5',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'f5b',
      name: '',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiez5: [
    {
      id: 'fdiez5a',
      name: 'F-#-5',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'fdiez5b',
      name: '',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  G5: [
    {
      id: 'g5a',
      name: 'G5',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'g5b',
      name: '',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiez5: [
    {
      id: 'gdiez5a',
      name: 'G-#-5',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'gdiez5b',
      name: '',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: null },
        { string: 4, fret: null },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiezm: [
    {
      id: 'ddiezma',
      name: 'D-#-m',
      firstFret: 5,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'ddiezmb',
      name: '',
      firstFret: 10,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiezm: [
    {
      id: 'gdiezma',
      name: 'G-#-m',
      firstFret: 10,
      frets: 3,
      hasBarre: true,
      barreShort: 1,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 2 },
        { string: 3, fret: 3 },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: null },
      ],
    },
    {
      id: 'gdiezmb',
      name: '',
      firstFret: 3,
      frets: 3,
      hasBarre: true,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 3 },
        { string: 6, fret: 1 },
      ],
    },
  ],

  Asus2: [
    {
      id: 'asus2',
      name: 'Asus2',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Asus4: [
    {
      id: 'asus4',
      name: 'Asus4',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  A7sus4: [
    {
      id: 'a7sus4',
      name: 'A7sus4',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Amaj7: [
    {
      id: 'amaj7',
      name: 'Amaj7',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adim: [
    {
      id: 'adim',
      name: 'Adim',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adim7: [
    {
      id: 'adim7',
      name: 'Adim7',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Aaug: [
    {
      id: 'aaug',
      name: 'Aaug',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  A9: [
    {
      id: 'a9',
      name: 'A9',
      firstFret: 4,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adiezsus2: [
    {
      id: 'adiezsus2',
      name: 'A-#-sus2',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adiezsus4: [
    {
      id: 'adiezsus4',
      name: 'A-#-sus4',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adiez7sus4: [
    {
      id: 'adiez7sus4',
      name: 'A-#-7sus4',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adiezmaj7: [
    {
      id: 'adiezmaj7',
      name: 'A-#-maj7',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adiezdim: [
    {
      id: 'adiezdim',
      name: 'A-#-dim',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adiezdim7: [
    {
      id: 'adiezdim7',
      name: 'A-#-dim7',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adiezaug: [
    {
      id: 'adiezaug',
      name: 'A-#-aug',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Adiez9: [
    {
      id: 'adiez9',
      name: 'A-#-9',
      firstFret: 5,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Bsus2: [
    {
      id: 'bsus2',
      name: 'Bsus2',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Bsus4: [
    {
      id: 'bsus4',
      name: 'Bsus4',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  B7sus4: [
    {
      id: 'b7sus4',
      name: 'B7sus4',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Bmaj7: [
    {
      id: 'bmaj7',
      name: 'Bmaj7',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Bdim: [
    {
      id: 'bdim',
      name: 'Bdim',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Bdim7: [
    {
      id: 'bdim7',
      name: 'Bdim7',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Baug: [
    {
      id: 'baug',
      name: 'Baug',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  B9: [
    {
      id: 'b9',
      name: 'B9',
      firstFret: 6,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Csus2: [
    {
      id: 'csus2',
      name: 'Csus2',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Csus4: [
    {
      id: 'csus4',
      name: 'Csus4',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  C7sus4: [
    {
      id: 'c7sus4',
      name: 'C7sus4',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cmaj7: [
    {
      id: 'cmaj7',
      name: 'Cmaj7',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdim: [
    {
      id: 'cdim',
      name: 'Cdim',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdim7: [
    {
      id: 'cdim7',
      name: 'Cdim7',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Caug: [
    {
      id: 'caug',
      name: 'Caug',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  C9: [
    {
      id: 'c9',
      name: 'C9',
      firstFret: 7,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiezsus2: [
    {
      id: 'cdiezsus2',
      name: 'C-#-sus2',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiezsus4: [
    {
      id: 'cdiezsus4',
      name: 'C-#-sus4',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiez7sus4: [
    {
      id: 'cdiez7sus4',
      name: 'C-#-7sus4',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiezmaj7: [
    {
      id: 'cdiezmaj7',
      name: 'C-#-maj7',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiezdim: [
    {
      id: 'cdiezdim',
      name: 'C-#-dim',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiezdim7: [
    {
      id: 'cdiezdim7',
      name: 'C-#-dim7',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiezaug: [
    {
      id: 'cdiezaug',
      name: 'C-#-aug',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Cdiez9: [
    {
      id: 'cdiez9',
      name: 'C-#-9',
      firstFret: 8,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Dsus2: [
    {
      id: 'dsus2',
      name: 'Dsus2',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Dsus4: [
    {
      id: 'dsus4',
      name: 'Dsus4',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  D7sus4: [
    {
      id: 'd7sus4',
      name: 'D7sus4',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Dmaj7: [
    {
      id: 'dmaj7',
      name: 'Dmaj7',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddim: [
    {
      id: 'ddim',
      name: 'Ddim',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddim7: [
    {
      id: 'ddim7',
      name: 'Ddim7',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Daug: [
    {
      id: 'daug',
      name: 'Daug',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  D9: [
    {
      id: 'd9',
      name: 'D9',
      firstFret: 9,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiezsus2: [
    {
      id: 'ddiezsus2',
      name: 'D-#-sus2',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiezsus4: [
    {
      id: 'ddiezsus4',
      name: 'D-#-sus4',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiez7sus4: [
    {
      id: 'ddiez7sus4',
      name: 'D-#-7sus4',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiezmaj7: [
    {
      id: 'ddiezmaj7',
      name: 'D-#-maj7',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiezdim: [
    {
      id: 'ddiezdim',
      name: 'D-#-dim',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiezdim7: [
    {
      id: 'ddiezdim7',
      name: 'D-#-dim7',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiezaug: [
    {
      id: 'ddiezaug',
      name: 'D-#-aug',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Ddiez9: [
    {
      id: 'ddiez9',
      name: 'D-#-9',
      firstFret: 10,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Esus2: [
    {
      id: 'esus2',
      name: 'Esus2',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 2 },
        { string: 2, fret: 0 },
        { string: 3, fret: null },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 0 },
      ],
    },
  ],
  Esus4: [
    {
      id: 'esus4',
      name: 'Esus4',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 0 },
        { string: 3, fret: null },
        { string: 4, fret: 2 },
        { string: 5, fret: 0 },
        { string: 6, fret: 0 },
      ],
    },
  ],
  E7sus4: [
    {
      id: 'e7sus4',
      name: 'E7sus4',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 0 },
        { string: 2, fret: 0 },
        { string: 3, fret: null },
        { string: 4, fret: 0 },
        { string: 5, fret: 0 },
        { string: 6, fret: 0 },
      ],
    },
  ],
  Emaj7: [
    {
      id: 'emaj7',
      name: 'Emaj7',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 0 },
        { string: 2, fret: 0 },
        { string: 3, fret: 1 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 0 },
      ],
    },
  ],
  Edim: [
    {
      id: 'edim',
      name: 'Edim',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 0 },
        { string: 4, fret: 2 },
        { string: 5, fret: 1 },
        { string: 6, fret: 0 },
      ],
    },
  ],
  Edim7: [
    {
      id: 'edim7',
      name: 'Edim7',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 0 },
        { string: 4, fret: 2 },
        { string: 5, fret: 1 },
        { string: 6, fret: 0 },
      ],
    },
  ],
  Eaug: [
    {
      id: 'eaug',
      name: 'Eaug',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: 1 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 0 },
      ],
    },
  ],
  E9: [
    {
      id: 'e9',
      name: 'E9',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 2 },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 0 },
        { string: 5, fret: null },
        { string: 6, fret: 0 },
      ],
    },
  ],
  Fsus2: [
    {
      id: 'fsus2',
      name: 'Fsus2',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fsus4: [
    {
      id: 'fsus4',
      name: 'Fsus4',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  F7sus4: [
    {
      id: 'f7sus4',
      name: 'F7sus4',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fmaj7: [
    {
      id: 'fmaj7',
      name: 'Fmaj7',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdim: [
    {
      id: 'fdim',
      name: 'Fdim',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdim7: [
    {
      id: 'fdim7',
      name: 'Fdim7',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Faug: [
    {
      id: 'faug',
      name: 'Faug',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  F9: [
    {
      id: 'f9',
      name: 'F9',
      firstFret: 0,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiezsus2: [
    {
      id: 'fdiezsus2',
      name: 'F-#-sus2',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiezsus4: [
    {
      id: 'fdiezsus4',
      name: 'F-#-sus4',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiez7sus4: [
    {
      id: 'fdiez7sus4',
      name: 'F-#-7sus4',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiezmaj7: [
    {
      id: 'fdiezmaj7',
      name: 'F-#-maj7',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiezdim: [
    {
      id: 'fdiezdim',
      name: 'F-#-dim',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiezdim7: [
    {
      id: 'fdiezdim7',
      name: 'F-#-dim7',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiezaug: [
    {
      id: 'fdiezaug',
      name: 'F-#-aug',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Fdiez9: [
    {
      id: 'fdiez9',
      name: 'F-#-9',
      firstFret: 1,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gsus2: [
    {
      id: 'gsus2',
      name: 'Gsus2',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gsus4: [
    {
      id: 'gsus4',
      name: 'Gsus4',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  G7sus4: [
    {
      id: 'g7sus4',
      name: 'G7sus4',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gmaj7: [
    {
      id: 'gmaj7',
      name: 'Gmaj7',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdim: [
    {
      id: 'gdim',
      name: 'Gdim',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdim7: [
    {
      id: 'gdim7',
      name: 'Gdim7',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gaug: [
    {
      id: 'gaug',
      name: 'Gaug',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  G9: [
    {
      id: 'g9',
      name: 'G9',
      firstFret: 2,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiezsus2: [
    {
      id: 'gdiezsus2',
      name: 'G-#-sus2',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiezsus4: [
    {
      id: 'gdiezsus4',
      name: 'G-#-sus4',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 3 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiez7sus4: [
    {
      id: 'gdiez7sus4',
      name: 'G-#-7sus4',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: null },
        { string: 4, fret: 1 },
        { string: 5, fret: 1 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiezmaj7: [
    {
      id: 'gdiezmaj7',
      name: 'G-#-maj7',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 1 },
        { string: 2, fret: 1 },
        { string: 3, fret: 2 },
        { string: 4, fret: 2 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiezdim: [
    {
      id: 'gdiezdim',
      name: 'G-#-dim',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: null },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiezdim7: [
    {
      id: 'gdiezdim7',
      name: 'G-#-dim7',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 3 },
        { string: 3, fret: 1 },
        { string: 4, fret: 3 },
        { string: 5, fret: 2 },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiezaug: [
    {
      id: 'gdiezaug',
      name: 'G-#-aug',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: null },
        { string: 2, fret: 2 },
        { string: 3, fret: 2 },
        { string: 4, fret: 3 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
  Gdiez9: [
    {
      id: 'gdiez9',
      name: 'G-#-9',
      firstFret: 3,
      frets: 3,
      hasBarre: false,
      points: [
        { string: 1, fret: 3 },
        { string: 2, fret: null },
        { string: 3, fret: 2 },
        { string: 4, fret: 1 },
        { string: 5, fret: null },
        { string: 6, fret: 1 },
      ],
    },
  ],
}
